try:
    import builtins
except ImportError:
    import __builtin__ as builtins
import datetime
import subprocess
import os

Import("env")

def get_git_rev():
    try:
        revision = subprocess.check_output(["git", "rev-parse", "HEAD"]).strip().decode("utf-8")
        return revision
    except Exception:
        return "UNKNOWN_REV"

def get_git_branch():
    try:
        branch = subprocess.check_output(["git", "rev-parse", "--abbrev-ref", "HEAD"]).strip().decode("utf-8")
        return branch
    except Exception:
        return "UNKNOWN_BRANCH"

def generate_build_info():
    revision = get_git_rev()
    branch = get_git_branch()
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Check GCC version
    try:
        gcc_ver = subprocess.check_output(["xtensa-esp32s3-elf-g++", "--version"]).splitlines()[0].decode("utf-8")
    except:
        gcc_ver = "Unknown GCC"

    content = f"""/**
 * @file build_info.h
 * @brief Auto-generated build information
 * @note Generated by scripts/generate_build_info.py
 */
#pragma once

#define BUILD_TIMESTAMP "{timestamp}"
#define BUILD_GIT_HASH  "{revision}"
#define BUILD_GIT_BRANCH "{branch}"
#define BUILD_COMPILER  "{gcc_ver}"
#define BUILD_BY        "{os.environ.get('USERNAME', 'Unknown User')}"

// Short hash (first 7 chars)
#define BUILD_GIT_HASH_SHORT "{revision[:7]}"

"""
    
    output_file = os.path.join(env.subst("$PROJECT_DIR"), "include", "build_info.h")
    
    # Only write if changed to prevent unnecessary rebuilds
    if os.path.exists(output_file):
        with open(output_file, "r") as f:
            if f.read() == content:
                print("Build info unchanged.")
                return

    with open(output_file, "w") as f:
        f.write(content)
    
    print(f"Generated build_info.h -> {revision[:7]}")

# Run unconditionally
generate_build_info()
