/**
 * @file build_info.h
 * @brief Auto-generated build information
 * @note Generated by scripts/generate_build_info.py
 */
#pragma once

#define BUILD_TIMESTAMP "2026-01-09 01:56:33"
#define BUILD_GIT_HASH  "b4428e5077fad055b281bdb6e5a3e17f314f8b08"
#define BUILD_GIT_BRANCH "main"
#define BUILD_COMPILER  "xtensa-esp32s3-elf-g++ (crosstool-NG esp-2021r2-patch5) 8.4.0"
#define BUILD_BY        "leleb"

// Short hash (first 7 chars)
#define BUILD_GIT_HASH_SHORT "b4428e5"

